// Command schema-gen creates Go wire types from the official ACP JSON schema.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"unicode"
)

type schema map[string]any

func main() {
	path := flag.String("schema", "", "official ACP schema.json")
	version := flag.String("version", "", "ACP schema package version")
	wantSHA := flag.String("sha256", "", "expected schema SHA-256")
	out := flag.String("out", "types_generated.go", "output file")
	flag.Parse()
	if *path == "" || *version == "" {
		fatalf("-schema and -version are required")
	}
	b, err := os.ReadFile(*path)
	if err != nil {
		fatalf("read schema: %v", err)
	}
	var root schema
	if err := json.Unmarshal(b, &root); err != nil {
		fatalf("decode schema: %v", err)
	}
	defsAny, ok := root["$defs"].(map[string]any)
	if !ok {
		fatalf("schema has no $defs object")
	}
	defs := make(map[string]schema, len(defsAny))
	for name, raw := range defsAny {
		if s, ok := raw.(map[string]any); ok {
			defs[name] = s
		}
	}
	names := make([]string, 0, len(defs))
	for name := range defs {
		names = append(names, name)
	}
	sort.Strings(names)

	digest := sha256.Sum256(b)
	gotSHA := hex.EncodeToString(digest[:])
	if *wantSHA == "" || gotSHA != *wantSHA {
		fatalf("schema SHA-256 is %s, want %s", gotSHA, *wantSHA)
	}
	var dst bytes.Buffer
	fmt.Fprintf(&dst, "// Code generated by go generate ./internal/acp; DO NOT EDIT.\n")
	fmt.Fprintf(&dst, "// Source: @agentclientprotocol/sdk %s schema/schema.json.\n\n", *version)
	fmt.Fprintln(&dst, "package acp")
	fmt.Fprintln(&dst, "\nimport \"encoding/json\"")
	fmt.Fprintf(&dst, "\nconst SchemaPackageVersion = %q\nconst SchemaSHA256 = %q\n", *version, gotSHA)
	for _, name := range names {
		emit(&dst, name, defs[name])
	}
	formatted, err := format.Source(dst.Bytes())
	if err != nil {
		fatalf("format generated source: %v\n%s", err, dst.String())
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func emit(dst *bytes.Buffer, name string, s schema) {
	typeName := goName(name)
	if schemaType(s) != "object" {
		fmt.Fprintf(dst, "\ntype %s %s\n", typeName, goType(s))
		return
	}
	props, _ := s["properties"].(map[string]any)
	required := map[string]bool{}
	if list, ok := s["required"].([]any); ok {
		for _, v := range list {
			if n, ok := v.(string); ok {
				required[n] = true
			}
		}
	}
	keys := make([]string, 0, len(props))
	for key := range props {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	fmt.Fprintf(dst, "\ntype %s struct {\n", typeName)
	for _, key := range keys {
		p, _ := props[key].(map[string]any)
		tag := key
		if !required[key] {
			tag += ",omitempty"
		}
		fmt.Fprintf(dst, "\t%s %s `json:%q`\n", goName(key), goType(p), tag)
	}
	fmt.Fprintln(dst, "}")
}

func goType(s schema) string {
	if ref, ok := s["$ref"].(string); ok {
		return goName(ref[strings.LastIndex(ref, "/")+1:])
	}
	if all, ok := s["allOf"].([]any); ok && len(all) == 1 {
		if child, ok := all[0].(map[string]any); ok {
			return goType(child)
		}
	}
	if variants, ok := s["anyOf"].([]any); ok {
		var choices []schema
		for _, raw := range variants {
			if child, ok := raw.(map[string]any); ok && schemaType(child) != "null" {
				choices = append(choices, child)
			}
		}
		if len(choices) == 1 {
			return goType(choices[0])
		}
		return "json.RawMessage"
	}
	switch schemaType(s) {
	case "string":
		return "string"
	case "integer":
		return "int64"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		if item, ok := s["items"].(map[string]any); ok {
			return "[]" + goType(item)
		}
		return "[]json.RawMessage"
	case "object":
		return "map[string]json.RawMessage"
	default:
		return "json.RawMessage"
	}
}

func schemaType(s schema) string {
	if typ, ok := s["type"].(string); ok {
		return typ
	}
	if types, ok := s["type"].([]any); ok {
		for _, raw := range types {
			if typ, ok := raw.(string); ok && typ != "null" {
				return typ
			}
		}
		return "null"
	}
	if _, ok := s["properties"]; ok {
		return "object"
	}
	return ""
}

func goName(s string) string {
	var out []rune
	upper := true
	for _, r := range s {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upper = true
			continue
		}
		if upper {
			r = unicode.ToUpper(r)
			upper = false
		}
		out = append(out, r)
	}
	if len(out) == 0 {
		return "Value"
	}
	if unicode.IsDigit(out[0]) {
		out = append([]rune{'X'}, out...)
	}
	return string(out)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "schema-gen: "+format+"\n", args...)
	os.Exit(1)
}
