// Code generated by go generate ./internal/acp; DO NOT EDIT.
// Source: @agentclientprotocol/sdk 1.2.1 schema/schema.json.

package acp

import "encoding/json"

const SchemaPackageVersion = "1.2.1"
const SchemaSHA256 = "8bdfd8347ce8bd2c8620b71bfd5460625f91c7db47a51268bb42b67014ea5b1f"

type AcceptNesNotification struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	Id        NesSuggestionId            `json:"id"`
	SessionId SessionId                  `json:"sessionId"`
}

type AgentAuthCapabilities struct {
	Meta   map[string]json.RawMessage `json:"_meta,omitempty"`
	Logout LogoutCapabilities         `json:"logout,omitempty"`
}

type AgentCapabilities struct {
	Meta                map[string]json.RawMessage `json:"_meta,omitempty"`
	Auth                AgentAuthCapabilities      `json:"auth,omitempty"`
	LoadSession         bool                       `json:"loadSession,omitempty"`
	McpCapabilities     McpCapabilities            `json:"mcpCapabilities,omitempty"`
	Nes                 NesCapabilities            `json:"nes,omitempty"`
	PositionEncoding    PositionEncodingKind       `json:"positionEncoding,omitempty"`
	PromptCapabilities  PromptCapabilities         `json:"promptCapabilities,omitempty"`
	Providers           ProvidersCapabilities      `json:"providers,omitempty"`
	SessionCapabilities SessionCapabilities        `json:"sessionCapabilities,omitempty"`
}

type AgentNotification struct {
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

type AgentRequest struct {
	Id     RequestId       `json:"id"`
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

type AgentResponse json.RawMessage

type Annotations struct {
	Meta         map[string]json.RawMessage `json:"_meta,omitempty"`
	Audience     []Role                     `json:"audience,omitempty"`
	LastModified string                     `json:"lastModified,omitempty"`
	Priority     float64                    `json:"priority,omitempty"`
}

type AudioContent struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Annotations Annotations                `json:"annotations,omitempty"`
	Data        string                     `json:"data"`
	MimeType    string                     `json:"mimeType"`
}

type AuthCapabilities struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	Terminal bool                       `json:"terminal,omitempty"`
}

type AuthEnvVar struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	Label    string                     `json:"label,omitempty"`
	Name     string                     `json:"name"`
	Optional bool                       `json:"optional,omitempty"`
	Secret   bool                       `json:"secret,omitempty"`
}

type AuthMethod json.RawMessage

type AuthMethodAgent struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Description string                     `json:"description,omitempty"`
	Id          AuthMethodId               `json:"id"`
	Name        string                     `json:"name"`
}

type AuthMethodEnvVar struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Description string                     `json:"description,omitempty"`
	Id          AuthMethodId               `json:"id"`
	Link        string                     `json:"link,omitempty"`
	Name        string                     `json:"name"`
	Vars        []AuthEnvVar               `json:"vars"`
}

type AuthMethodId string

type AuthMethodTerminal struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Args        []string                   `json:"args,omitempty"`
	Description string                     `json:"description,omitempty"`
	Env         map[string]json.RawMessage `json:"env,omitempty"`
	Id          AuthMethodId               `json:"id"`
	Name        string                     `json:"name"`
}

type AuthenticateRequest struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	MethodId AuthMethodId               `json:"methodId"`
}

type AuthenticateResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type AvailableCommand struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Description string                     `json:"description"`
	Input       AvailableCommandInput      `json:"input,omitempty"`
	Name        string                     `json:"name"`
}

type AvailableCommandInput UnstructuredCommandInput

type AvailableCommandsUpdate struct {
	Meta              map[string]json.RawMessage `json:"_meta,omitempty"`
	AvailableCommands []AvailableCommand         `json:"availableCommands"`
}

type BlobResourceContents struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	Blob     string                     `json:"blob"`
	MimeType string                     `json:"mimeType,omitempty"`
	Uri      string                     `json:"uri"`
}

type BooleanConfigOptionCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type BooleanPropertySchema struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Default     bool                       `json:"default,omitempty"`
	Description string                     `json:"description,omitempty"`
	Title       string                     `json:"title,omitempty"`
}

type CancelNotification struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId SessionId                  `json:"sessionId"`
}

type CancelRequestNotification struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	RequestId RequestId                  `json:"requestId"`
}

type ClientCapabilities struct {
	Meta              map[string]json.RawMessage `json:"_meta,omitempty"`
	Auth              AuthCapabilities           `json:"auth,omitempty"`
	Elicitation       ElicitationCapabilities    `json:"elicitation,omitempty"`
	Fs                FileSystemCapabilities     `json:"fs,omitempty"`
	Nes               ClientNesCapabilities      `json:"nes,omitempty"`
	Plan              PlanCapabilities           `json:"plan,omitempty"`
	PositionEncodings []PositionEncodingKind     `json:"positionEncodings,omitempty"`
	Session           ClientSessionCapabilities  `json:"session,omitempty"`
	Terminal          bool                       `json:"terminal,omitempty"`
}

type ClientNesCapabilities struct {
	Meta             map[string]json.RawMessage      `json:"_meta,omitempty"`
	Jump             NesJumpCapabilities             `json:"jump,omitempty"`
	Rename           NesRenameCapabilities           `json:"rename,omitempty"`
	SearchAndReplace NesSearchAndReplaceCapabilities `json:"searchAndReplace,omitempty"`
}

type ClientNotification struct {
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

type ClientRequest struct {
	Id     RequestId       `json:"id"`
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

type ClientResponse json.RawMessage

type ClientSessionCapabilities struct {
	Meta          map[string]json.RawMessage       `json:"_meta,omitempty"`
	ConfigOptions SessionConfigOptionsCapabilities `json:"configOptions,omitempty"`
}

type CloseNesRequest struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId SessionId                  `json:"sessionId"`
}

type CloseNesResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type CloseSessionRequest struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId SessionId                  `json:"sessionId"`
}

type CloseSessionResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type CompleteElicitationNotification struct {
	Meta          map[string]json.RawMessage `json:"_meta,omitempty"`
	ElicitationId ElicitationId              `json:"elicitationId"`
}

type ConfigOptionUpdate struct {
	Meta          map[string]json.RawMessage `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption      `json:"configOptions"`
}

type ConnectMcpRequest struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	ServerId McpServerAcpId             `json:"serverId"`
}

type ConnectMcpResponse struct {
	Meta         map[string]json.RawMessage `json:"_meta,omitempty"`
	ConnectionId McpConnectionId            `json:"connectionId"`
}

type Content struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Content ContentBlock               `json:"content"`
}

type ContentBlock json.RawMessage

type ContentChunk struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	Content   ContentBlock               `json:"content"`
	MessageId MessageId                  `json:"messageId,omitempty"`
}

type Cost struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	Amount   float64                    `json:"amount"`
	Currency string                     `json:"currency"`
}

type CreateElicitationRequest struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Message string                     `json:"message"`
}

type CreateElicitationResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type CreateTerminalRequest struct {
	Meta            map[string]json.RawMessage `json:"_meta,omitempty"`
	Args            []string                   `json:"args,omitempty"`
	Command         string                     `json:"command"`
	Cwd             string                     `json:"cwd,omitempty"`
	Env             []EnvVariable              `json:"env,omitempty"`
	OutputByteLimit int64                      `json:"outputByteLimit,omitempty"`
	SessionId       SessionId                  `json:"sessionId"`
}

type CreateTerminalResponse struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	TerminalId TerminalId                 `json:"terminalId"`
}

type CurrentModeUpdate struct {
	Meta          map[string]json.RawMessage `json:"_meta,omitempty"`
	CurrentModeId SessionModeId              `json:"currentModeId"`
}

type DeleteSessionRequest struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId SessionId                  `json:"sessionId"`
}

type DeleteSessionResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type DidChangeDocumentNotification struct {
	Meta           map[string]json.RawMessage       `json:"_meta,omitempty"`
	ContentChanges []TextDocumentContentChangeEvent `json:"contentChanges"`
	SessionId      SessionId                        `json:"sessionId"`
	Uri            string                           `json:"uri"`
	Version        int64                            `json:"version"`
}

type DidCloseDocumentNotification struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId SessionId                  `json:"sessionId"`
	Uri       string                     `json:"uri"`
}

type DidFocusDocumentNotification struct {
	Meta         map[string]json.RawMessage `json:"_meta,omitempty"`
	Position     Position                   `json:"position"`
	SessionId    SessionId                  `json:"sessionId"`
	Uri          string                     `json:"uri"`
	Version      int64                      `json:"version"`
	VisibleRange Range                      `json:"visibleRange"`
}

type DidOpenDocumentNotification struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	LanguageId string                     `json:"languageId"`
	SessionId  SessionId                  `json:"sessionId"`
	Text       string                     `json:"text"`
	Uri        string                     `json:"uri"`
	Version    int64                      `json:"version"`
}

type DidSaveDocumentNotification struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId SessionId                  `json:"sessionId"`
	Uri       string                     `json:"uri"`
}

type Diff struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	NewText string                     `json:"newText"`
	OldText string                     `json:"oldText,omitempty"`
	Path    string                     `json:"path"`
}

type DisableProviderRequest struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	ProviderId ProviderId                 `json:"providerId"`
}

type DisableProviderResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type DisconnectMcpRequest struct {
	Meta         map[string]json.RawMessage `json:"_meta,omitempty"`
	ConnectionId McpConnectionId            `json:"connectionId"`
}

type DisconnectMcpResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type ElicitationAcceptAction struct {
	Content map[string]json.RawMessage `json:"content,omitempty"`
}

type ElicitationCapabilities struct {
	Meta map[string]json.RawMessage  `json:"_meta,omitempty"`
	Form ElicitationFormCapabilities `json:"form,omitempty"`
	Url  ElicitationUrlCapabilities  `json:"url,omitempty"`
}

type ElicitationContentValue json.RawMessage

type ElicitationFormCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type ElicitationFormMode struct {
	RequestedSchema ElicitationSchema `json:"requestedSchema"`
}

type ElicitationId string

type ElicitationPropertySchema json.RawMessage

type ElicitationRequestScope struct {
	RequestId RequestId `json:"requestId"`
}

type ElicitationSchema struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Description string                     `json:"description,omitempty"`
	Properties  map[string]json.RawMessage `json:"properties,omitempty"`
	Required    []string                   `json:"required,omitempty"`
	Title       string                     `json:"title,omitempty"`
	Type        ElicitationSchemaType      `json:"type,omitempty"`
}

type ElicitationSchemaType json.RawMessage

type ElicitationSessionScope struct {
	SessionId  SessionId  `json:"sessionId"`
	ToolCallId ToolCallId `json:"toolCallId,omitempty"`
}

type ElicitationUrlCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type ElicitationUrlMode struct {
	ElicitationId ElicitationId `json:"elicitationId"`
	Url           string        `json:"url"`
}

type EmbeddedResource struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Annotations Annotations                `json:"annotations,omitempty"`
	Resource    EmbeddedResourceResource   `json:"resource"`
}

type EmbeddedResourceResource json.RawMessage

type EnumOption struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Const       string                     `json:"const"`
	Description string                     `json:"description,omitempty"`
	Title       string                     `json:"title"`
}

type EnvVariable struct {
	Meta  map[string]json.RawMessage `json:"_meta,omitempty"`
	Name  string                     `json:"name"`
	Value string                     `json:"value"`
}

type Error struct {
	Code    ErrorCode       `json:"code"`
	Data    json.RawMessage `json:"data,omitempty"`
	Message string          `json:"message"`
}

type ErrorCode json.RawMessage

type ExtNotification json.RawMessage

type ExtRequest json.RawMessage

type ExtResponse json.RawMessage

type FileSystemCapabilities struct {
	Meta          map[string]json.RawMessage `json:"_meta,omitempty"`
	ReadTextFile  bool                       `json:"readTextFile,omitempty"`
	WriteTextFile bool                       `json:"writeTextFile,omitempty"`
}

type ForkSessionRequest struct {
	Meta                  map[string]json.RawMessage `json:"_meta,omitempty"`
	AdditionalDirectories []string                   `json:"additionalDirectories,omitempty"`
	Cwd                   string                     `json:"cwd"`
	McpServers            []McpServer                `json:"mcpServers,omitempty"`
	SessionId             SessionId                  `json:"sessionId"`
}

type ForkSessionResponse struct {
	Meta          map[string]json.RawMessage `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption      `json:"configOptions,omitempty"`
	Modes         SessionModeState           `json:"modes,omitempty"`
	SessionId     SessionId                  `json:"sessionId"`
}

type HttpHeader struct {
	Meta  map[string]json.RawMessage `json:"_meta,omitempty"`
	Name  string                     `json:"name"`
	Value string                     `json:"value"`
}

type ImageContent struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Annotations Annotations                `json:"annotations,omitempty"`
	Data        string                     `json:"data"`
	MimeType    string                     `json:"mimeType"`
	Uri         string                     `json:"uri,omitempty"`
}

type Implementation struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Name    string                     `json:"name"`
	Title   string                     `json:"title,omitempty"`
	Version string                     `json:"version"`
}

type InitializeRequest struct {
	Meta               map[string]json.RawMessage `json:"_meta,omitempty"`
	ClientCapabilities ClientCapabilities         `json:"clientCapabilities,omitempty"`
	ClientInfo         Implementation             `json:"clientInfo,omitempty"`
	ProtocolVersion    ProtocolVersion            `json:"protocolVersion"`
}

type InitializeResponse struct {
	Meta              map[string]json.RawMessage `json:"_meta,omitempty"`
	AgentCapabilities AgentCapabilities          `json:"agentCapabilities,omitempty"`
	AgentInfo         Implementation             `json:"agentInfo,omitempty"`
	AuthMethods       []AuthMethod               `json:"authMethods,omitempty"`
	ProtocolVersion   ProtocolVersion            `json:"protocolVersion"`
}

type IntegerPropertySchema struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Default     int64                      `json:"default,omitempty"`
	Description string                     `json:"description,omitempty"`
	Maximum     int64                      `json:"maximum,omitempty"`
	Minimum     int64                      `json:"minimum,omitempty"`
	Title       string                     `json:"title,omitempty"`
}

type KillTerminalRequest struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId  SessionId                  `json:"sessionId"`
	TerminalId TerminalId                 `json:"terminalId"`
}

type KillTerminalResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type ListProvidersRequest struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type ListProvidersResponse struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	Providers []ProviderInfo             `json:"providers"`
}

type ListSessionsRequest struct {
	Meta   map[string]json.RawMessage `json:"_meta,omitempty"`
	Cursor string                     `json:"cursor,omitempty"`
	Cwd    string                     `json:"cwd,omitempty"`
}

type ListSessionsResponse struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	NextCursor string                     `json:"nextCursor,omitempty"`
	Sessions   []SessionInfo              `json:"sessions"`
}

type LlmProtocol json.RawMessage

type LoadSessionRequest struct {
	Meta                  map[string]json.RawMessage `json:"_meta,omitempty"`
	AdditionalDirectories []string                   `json:"additionalDirectories,omitempty"`
	Cwd                   string                     `json:"cwd"`
	McpServers            []McpServer                `json:"mcpServers"`
	SessionId             SessionId                  `json:"sessionId"`
}

type LoadSessionResponse struct {
	Meta          map[string]json.RawMessage `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption      `json:"configOptions,omitempty"`
	Modes         SessionModeState           `json:"modes,omitempty"`
}

type LogoutCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type LogoutRequest struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type LogoutResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type McpCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
	Acp  bool                       `json:"acp,omitempty"`
	Http bool                       `json:"http,omitempty"`
	Sse  bool                       `json:"sse,omitempty"`
}

type McpConnectionId string

type McpServer json.RawMessage

type McpServerAcp struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	Name     string                     `json:"name"`
	ServerId McpServerAcpId             `json:"serverId"`
}

type McpServerAcpId string

type McpServerHttp struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Headers []HttpHeader               `json:"headers"`
	Name    string                     `json:"name"`
	Url     string                     `json:"url"`
}

type McpServerSse struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Headers []HttpHeader               `json:"headers"`
	Name    string                     `json:"name"`
	Url     string                     `json:"url"`
}

type McpServerStdio struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Args    []string                   `json:"args"`
	Command string                     `json:"command"`
	Env     []EnvVariable              `json:"env"`
	Name    string                     `json:"name"`
}

type MessageId string

type MessageMcpNotification struct {
	Meta         map[string]json.RawMessage `json:"_meta,omitempty"`
	ConnectionId McpConnectionId            `json:"connectionId"`
	Method       string                     `json:"method"`
	Params       map[string]json.RawMessage `json:"params,omitempty"`
}

type MessageMcpRequest struct {
	Meta         map[string]json.RawMessage `json:"_meta,omitempty"`
	ConnectionId McpConnectionId            `json:"connectionId"`
	Method       string                     `json:"method"`
	Params       map[string]json.RawMessage `json:"params,omitempty"`
}

type MessageMcpResponse json.RawMessage

type MultiSelectItems json.RawMessage

type MultiSelectPropertySchema struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Default     []string                   `json:"default,omitempty"`
	Description string                     `json:"description,omitempty"`
	Items       MultiSelectItems           `json:"items"`
	MaxItems    int64                      `json:"maxItems,omitempty"`
	MinItems    int64                      `json:"minItems,omitempty"`
	Title       string                     `json:"title,omitempty"`
}

type NesCapabilities struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Context NesContextCapabilities     `json:"context,omitempty"`
	Events  NesEventCapabilities       `json:"events,omitempty"`
}

type NesContextCapabilities struct {
	Meta            map[string]json.RawMessage     `json:"_meta,omitempty"`
	Diagnostics     NesDiagnosticsCapabilities     `json:"diagnostics,omitempty"`
	EditHistory     NesEditHistoryCapabilities     `json:"editHistory,omitempty"`
	OpenFiles       NesOpenFilesCapabilities       `json:"openFiles,omitempty"`
	RecentFiles     NesRecentFilesCapabilities     `json:"recentFiles,omitempty"`
	RelatedSnippets NesRelatedSnippetsCapabilities `json:"relatedSnippets,omitempty"`
	UserActions     NesUserActionsCapabilities     `json:"userActions,omitempty"`
}

type NesDiagnostic struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	Message  string                     `json:"message"`
	Range    Range                      `json:"range"`
	Severity NesDiagnosticSeverity      `json:"severity"`
	Uri      string                     `json:"uri"`
}

type NesDiagnosticSeverity json.RawMessage

type NesDiagnosticsCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type NesDocumentDidChangeCapabilities struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	SyncKind TextDocumentSyncKind       `json:"syncKind"`
}

type NesDocumentDidCloseCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type NesDocumentDidFocusCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type NesDocumentDidOpenCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type NesDocumentDidSaveCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type NesDocumentEventCapabilities struct {
	Meta      map[string]json.RawMessage       `json:"_meta,omitempty"`
	DidChange NesDocumentDidChangeCapabilities `json:"didChange,omitempty"`
	DidClose  NesDocumentDidCloseCapabilities  `json:"didClose,omitempty"`
	DidFocus  NesDocumentDidFocusCapabilities  `json:"didFocus,omitempty"`
	DidOpen   NesDocumentDidOpenCapabilities   `json:"didOpen,omitempty"`
	DidSave   NesDocumentDidSaveCapabilities   `json:"didSave,omitempty"`
}

type NesEditHistoryCapabilities struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	MaxCount int64                      `json:"maxCount,omitempty"`
}

type NesEditHistoryEntry struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
	Diff string                     `json:"diff"`
	Uri  string                     `json:"uri"`
}

type NesEditSuggestion struct {
	Meta           map[string]json.RawMessage `json:"_meta,omitempty"`
	CursorPosition Position                   `json:"cursorPosition,omitempty"`
	Edits          []NesTextEdit              `json:"edits"`
	Id             NesSuggestionId            `json:"id"`
	Uri            string                     `json:"uri"`
}

type NesEventCapabilities struct {
	Meta     map[string]json.RawMessage   `json:"_meta,omitempty"`
	Document NesDocumentEventCapabilities `json:"document,omitempty"`
}

type NesExcerpt struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	EndLine   int64                      `json:"endLine"`
	StartLine int64                      `json:"startLine"`
	Text      string                     `json:"text"`
}

type NesJumpCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type NesJumpSuggestion struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	Id       NesSuggestionId            `json:"id"`
	Position Position                   `json:"position"`
	Uri      string                     `json:"uri"`
}

type NesOpenFile struct {
	Meta          map[string]json.RawMessage `json:"_meta,omitempty"`
	LanguageId    string                     `json:"languageId"`
	LastFocusedMs int64                      `json:"lastFocusedMs,omitempty"`
	Uri           string                     `json:"uri"`
	VisibleRange  Range                      `json:"visibleRange,omitempty"`
}

type NesOpenFilesCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type NesRecentFile struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	LanguageId string                     `json:"languageId"`
	Text       string                     `json:"text"`
	Uri        string                     `json:"uri"`
}

type NesRecentFilesCapabilities struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	MaxCount int64                      `json:"maxCount,omitempty"`
}

type NesRejectReason json.RawMessage

type NesRelatedSnippet struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	Excerpts []NesExcerpt               `json:"excerpts"`
	Uri      string                     `json:"uri"`
}

type NesRelatedSnippetsCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type NesRenameCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type NesRenameSuggestion struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	Id       NesSuggestionId            `json:"id"`
	NewName  string                     `json:"newName"`
	Position Position                   `json:"position"`
	Uri      string                     `json:"uri"`
}

type NesRepository struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	Name      string                     `json:"name"`
	Owner     string                     `json:"owner"`
	RemoteUrl string                     `json:"remoteUrl"`
}

type NesSearchAndReplaceCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type NesSearchAndReplaceSuggestion struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Id      NesSuggestionId            `json:"id"`
	IsRegex bool                       `json:"isRegex,omitempty"`
	Replace string                     `json:"replace"`
	Search  string                     `json:"search"`
	Uri     string                     `json:"uri"`
}

type NesSuggestContext struct {
	Meta            map[string]json.RawMessage `json:"_meta,omitempty"`
	Diagnostics     []NesDiagnostic            `json:"diagnostics,omitempty"`
	EditHistory     []NesEditHistoryEntry      `json:"editHistory,omitempty"`
	OpenFiles       []NesOpenFile              `json:"openFiles,omitempty"`
	RecentFiles     []NesRecentFile            `json:"recentFiles,omitempty"`
	RelatedSnippets []NesRelatedSnippet        `json:"relatedSnippets,omitempty"`
	UserActions     []NesUserAction            `json:"userActions,omitempty"`
}

type NesSuggestion json.RawMessage

type NesSuggestionId string

type NesTextEdit struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	NewText string                     `json:"newText"`
	Range   Range                      `json:"range"`
}

type NesTriggerKind json.RawMessage

type NesUserAction struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Action      string                     `json:"action"`
	Position    Position                   `json:"position"`
	TimestampMs int64                      `json:"timestampMs"`
	Uri         string                     `json:"uri"`
}

type NesUserActionsCapabilities struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	MaxCount int64                      `json:"maxCount,omitempty"`
}

type NewSessionRequest struct {
	Meta                  map[string]json.RawMessage `json:"_meta,omitempty"`
	AdditionalDirectories []string                   `json:"additionalDirectories,omitempty"`
	Cwd                   string                     `json:"cwd"`
	McpServers            []McpServer                `json:"mcpServers"`
}

type NewSessionResponse struct {
	Meta          map[string]json.RawMessage `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption      `json:"configOptions,omitempty"`
	Modes         SessionModeState           `json:"modes,omitempty"`
	SessionId     SessionId                  `json:"sessionId"`
}

type NumberPropertySchema struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Default     float64                    `json:"default,omitempty"`
	Description string                     `json:"description,omitempty"`
	Maximum     float64                    `json:"maximum,omitempty"`
	Minimum     float64                    `json:"minimum,omitempty"`
	Title       string                     `json:"title,omitempty"`
}

type PermissionOption struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	Kind     PermissionOptionKind       `json:"kind"`
	Name     string                     `json:"name"`
	OptionId PermissionOptionId         `json:"optionId"`
}

type PermissionOptionId string

type PermissionOptionKind json.RawMessage

type Plan struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Entries []PlanEntry                `json:"entries"`
}

type PlanCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type PlanEntry struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	Content  string                     `json:"content"`
	Priority PlanEntryPriority          `json:"priority"`
	Status   PlanEntryStatus            `json:"status"`
}

type PlanEntryPriority json.RawMessage

type PlanEntryStatus json.RawMessage

type PlanFile struct {
	Meta   map[string]json.RawMessage `json:"_meta,omitempty"`
	PlanId PlanId                     `json:"planId"`
	Uri    string                     `json:"uri"`
}

type PlanId string

type PlanItems struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Entries []PlanEntry                `json:"entries"`
	PlanId  PlanId                     `json:"planId"`
}

type PlanMarkdown struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Content string                     `json:"content"`
	PlanId  PlanId                     `json:"planId"`
}

type PlanRemoved struct {
	Meta   map[string]json.RawMessage `json:"_meta,omitempty"`
	PlanId PlanId                     `json:"planId"`
}

type PlanUpdate struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
	Plan PlanUpdateContent          `json:"plan"`
}

type PlanUpdateContent json.RawMessage

type Position struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	Character int64                      `json:"character"`
	Line      int64                      `json:"line"`
}

type PositionEncodingKind json.RawMessage

type PromptCapabilities struct {
	Meta            map[string]json.RawMessage `json:"_meta,omitempty"`
	Audio           bool                       `json:"audio,omitempty"`
	EmbeddedContext bool                       `json:"embeddedContext,omitempty"`
	Image           bool                       `json:"image,omitempty"`
}

type PromptRequest struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	Prompt    []ContentBlock             `json:"prompt"`
	SessionId SessionId                  `json:"sessionId"`
}

type PromptResponse struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	StopReason StopReason                 `json:"stopReason"`
	Usage      Usage                      `json:"usage,omitempty"`
}

type ProtocolVersion int64

type ProviderCurrentConfig struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	ApiType LlmProtocol                `json:"apiType"`
	BaseUrl string                     `json:"baseUrl"`
}

type ProviderId string

type ProviderInfo struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	Current    ProviderCurrentConfig      `json:"current,omitempty"`
	ProviderId ProviderId                 `json:"providerId"`
	Required   bool                       `json:"required"`
	Supported  []LlmProtocol              `json:"supported"`
}

type ProvidersCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type Range struct {
	Meta  map[string]json.RawMessage `json:"_meta,omitempty"`
	End   Position                   `json:"end"`
	Start Position                   `json:"start"`
}

type ReadTextFileRequest struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	Limit     int64                      `json:"limit,omitempty"`
	Line      int64                      `json:"line,omitempty"`
	Path      string                     `json:"path"`
	SessionId SessionId                  `json:"sessionId"`
}

type ReadTextFileResponse struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Content string                     `json:"content"`
}

type RejectNesNotification struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	Id        NesSuggestionId            `json:"id"`
	Reason    NesRejectReason            `json:"reason,omitempty"`
	SessionId SessionId                  `json:"sessionId"`
}

type ReleaseTerminalRequest struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId  SessionId                  `json:"sessionId"`
	TerminalId TerminalId                 `json:"terminalId"`
}

type ReleaseTerminalResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type RequestId json.RawMessage

type RequestPermissionOutcome json.RawMessage

type RequestPermissionRequest struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	Options   []PermissionOption         `json:"options"`
	SessionId SessionId                  `json:"sessionId"`
	ToolCall  ToolCallUpdate             `json:"toolCall"`
}

type RequestPermissionResponse struct {
	Meta    map[string]json.RawMessage `json:"_meta,omitempty"`
	Outcome RequestPermissionOutcome   `json:"outcome"`
}

type ResourceLink struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Annotations Annotations                `json:"annotations,omitempty"`
	Description string                     `json:"description,omitempty"`
	MimeType    string                     `json:"mimeType,omitempty"`
	Name        string                     `json:"name"`
	Size        int64                      `json:"size,omitempty"`
	Title       string                     `json:"title,omitempty"`
	Uri         string                     `json:"uri"`
}

type ResumeSessionRequest struct {
	Meta                  map[string]json.RawMessage `json:"_meta,omitempty"`
	AdditionalDirectories []string                   `json:"additionalDirectories,omitempty"`
	Cwd                   string                     `json:"cwd"`
	McpServers            []McpServer                `json:"mcpServers,omitempty"`
	SessionId             SessionId                  `json:"sessionId"`
}

type ResumeSessionResponse struct {
	Meta          map[string]json.RawMessage `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption      `json:"configOptions,omitempty"`
	Modes         SessionModeState           `json:"modes,omitempty"`
}

type Role json.RawMessage

type SelectedPermissionOutcome struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	OptionId PermissionOptionId         `json:"optionId"`
}

type SessionAdditionalDirectoriesCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type SessionCapabilities struct {
	Meta                  map[string]json.RawMessage               `json:"_meta,omitempty"`
	AdditionalDirectories SessionAdditionalDirectoriesCapabilities `json:"additionalDirectories,omitempty"`
	Close                 SessionCloseCapabilities                 `json:"close,omitempty"`
	Delete                SessionDeleteCapabilities                `json:"delete,omitempty"`
	Fork                  SessionForkCapabilities                  `json:"fork,omitempty"`
	List                  SessionListCapabilities                  `json:"list,omitempty"`
	Resume                SessionResumeCapabilities                `json:"resume,omitempty"`
}

type SessionCloseCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type SessionConfigBoolean struct {
	CurrentValue bool `json:"currentValue"`
}

type SessionConfigGroupId string

type SessionConfigId string

type SessionConfigOption struct {
	Meta        map[string]json.RawMessage  `json:"_meta,omitempty"`
	Category    SessionConfigOptionCategory `json:"category,omitempty"`
	Description string                      `json:"description,omitempty"`
	Id          SessionConfigId             `json:"id"`
	Name        string                      `json:"name"`
}

type SessionConfigOptionCategory json.RawMessage

type SessionConfigOptionsCapabilities struct {
	Meta    map[string]json.RawMessage      `json:"_meta,omitempty"`
	Boolean BooleanConfigOptionCapabilities `json:"boolean,omitempty"`
}

type SessionConfigSelect struct {
	CurrentValue SessionConfigValueId       `json:"currentValue"`
	Options      SessionConfigSelectOptions `json:"options"`
}

type SessionConfigSelectGroup struct {
	Meta    map[string]json.RawMessage  `json:"_meta,omitempty"`
	Group   SessionConfigGroupId        `json:"group"`
	Name    string                      `json:"name"`
	Options []SessionConfigSelectOption `json:"options"`
}

type SessionConfigSelectOption struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Description string                     `json:"description,omitempty"`
	Name        string                     `json:"name"`
	Value       SessionConfigValueId       `json:"value"`
}

type SessionConfigSelectOptions json.RawMessage

type SessionConfigValueId string

type SessionDeleteCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type SessionForkCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type SessionId string

type SessionInfo struct {
	Meta                  map[string]json.RawMessage `json:"_meta,omitempty"`
	AdditionalDirectories []string                   `json:"additionalDirectories,omitempty"`
	Cwd                   string                     `json:"cwd"`
	SessionId             SessionId                  `json:"sessionId"`
	Title                 string                     `json:"title,omitempty"`
	UpdatedAt             string                     `json:"updatedAt,omitempty"`
}

type SessionInfoUpdate struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	Title     string                     `json:"title,omitempty"`
	UpdatedAt string                     `json:"updatedAt,omitempty"`
}

type SessionListCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type SessionMode struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Description string                     `json:"description,omitempty"`
	Id          SessionModeId              `json:"id"`
	Name        string                     `json:"name"`
}

type SessionModeId string

type SessionModeState struct {
	Meta           map[string]json.RawMessage `json:"_meta,omitempty"`
	AvailableModes []SessionMode              `json:"availableModes"`
	CurrentModeId  SessionModeId              `json:"currentModeId"`
}

type SessionNotification struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId SessionId                  `json:"sessionId"`
	Update    SessionUpdate              `json:"update"`
}

type SessionResumeCapabilities struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type SessionUpdate json.RawMessage

type SetProviderRequest struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	ApiType    LlmProtocol                `json:"apiType"`
	BaseUrl    string                     `json:"baseUrl"`
	Headers    map[string]json.RawMessage `json:"headers,omitempty"`
	ProviderId ProviderId                 `json:"providerId"`
}

type SetProviderResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type SetSessionConfigOptionRequest struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	ConfigId  SessionConfigId            `json:"configId"`
	SessionId SessionId                  `json:"sessionId"`
}

type SetSessionConfigOptionResponse struct {
	Meta          map[string]json.RawMessage `json:"_meta,omitempty"`
	ConfigOptions []SessionConfigOption      `json:"configOptions"`
}

type SetSessionModeRequest struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	ModeId    SessionModeId              `json:"modeId"`
	SessionId SessionId                  `json:"sessionId"`
}

type SetSessionModeResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}

type StartNesRequest struct {
	Meta             map[string]json.RawMessage `json:"_meta,omitempty"`
	Repository       NesRepository              `json:"repository,omitempty"`
	WorkspaceFolders []WorkspaceFolder          `json:"workspaceFolders,omitempty"`
	WorkspaceUri     string                     `json:"workspaceUri,omitempty"`
}

type StartNesResponse struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId SessionId                  `json:"sessionId"`
}

type StopReason json.RawMessage

type StringFormat json.RawMessage

type StringMultiSelectItems struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
	Enum []string                   `json:"enum"`
}

type StringPropertySchema struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Default     string                     `json:"default,omitempty"`
	Description string                     `json:"description,omitempty"`
	Enum        []string                   `json:"enum,omitempty"`
	Format      StringFormat               `json:"format,omitempty"`
	MaxLength   int64                      `json:"maxLength,omitempty"`
	MinLength   int64                      `json:"minLength,omitempty"`
	OneOf       []EnumOption               `json:"oneOf,omitempty"`
	Pattern     string                     `json:"pattern,omitempty"`
	Title       string                     `json:"title,omitempty"`
}

type SuggestNesRequest struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Context     NesSuggestContext          `json:"context,omitempty"`
	Position    Position                   `json:"position"`
	Selection   Range                      `json:"selection,omitempty"`
	SessionId   SessionId                  `json:"sessionId"`
	TriggerKind NesTriggerKind             `json:"triggerKind"`
	Uri         string                     `json:"uri"`
	Version     int64                      `json:"version"`
}

type SuggestNesResponse struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Suggestions []NesSuggestion            `json:"suggestions"`
}

type Terminal struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	TerminalId TerminalId                 `json:"terminalId"`
}

type TerminalExitStatus struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	ExitCode int64                      `json:"exitCode,omitempty"`
	Signal   string                     `json:"signal,omitempty"`
}

type TerminalId string

type TerminalOutputRequest struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId  SessionId                  `json:"sessionId"`
	TerminalId TerminalId                 `json:"terminalId"`
}

type TerminalOutputResponse struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	ExitStatus TerminalExitStatus         `json:"exitStatus,omitempty"`
	Output     string                     `json:"output"`
	Truncated  bool                       `json:"truncated"`
}

type TextContent struct {
	Meta        map[string]json.RawMessage `json:"_meta,omitempty"`
	Annotations Annotations                `json:"annotations,omitempty"`
	Text        string                     `json:"text"`
}

type TextDocumentContentChangeEvent struct {
	Meta  map[string]json.RawMessage `json:"_meta,omitempty"`
	Range Range                      `json:"range,omitempty"`
	Text  string                     `json:"text"`
}

type TextDocumentSyncKind json.RawMessage

type TextResourceContents struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	MimeType string                     `json:"mimeType,omitempty"`
	Text     string                     `json:"text"`
	Uri      string                     `json:"uri"`
}

type TitledMultiSelectItems struct {
	Meta  map[string]json.RawMessage `json:"_meta,omitempty"`
	AnyOf []EnumOption               `json:"anyOf"`
}

type ToolCall struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	Content    []ToolCallContent          `json:"content,omitempty"`
	Kind       ToolKind                   `json:"kind,omitempty"`
	Locations  []ToolCallLocation         `json:"locations,omitempty"`
	RawInput   json.RawMessage            `json:"rawInput,omitempty"`
	RawOutput  json.RawMessage            `json:"rawOutput,omitempty"`
	Status     ToolCallStatus             `json:"status,omitempty"`
	Title      string                     `json:"title"`
	ToolCallId ToolCallId                 `json:"toolCallId"`
}

type ToolCallContent json.RawMessage

type ToolCallId string

type ToolCallLocation struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
	Line int64                      `json:"line,omitempty"`
	Path string                     `json:"path"`
}

type ToolCallStatus json.RawMessage

type ToolCallUpdate struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	Content    []ToolCallContent          `json:"content,omitempty"`
	Kind       ToolKind                   `json:"kind,omitempty"`
	Locations  []ToolCallLocation         `json:"locations,omitempty"`
	RawInput   json.RawMessage            `json:"rawInput,omitempty"`
	RawOutput  json.RawMessage            `json:"rawOutput,omitempty"`
	Status     ToolCallStatus             `json:"status,omitempty"`
	Title      string                     `json:"title,omitempty"`
	ToolCallId ToolCallId                 `json:"toolCallId"`
}

type ToolKind json.RawMessage

type UnstructuredCommandInput struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
	Hint string                     `json:"hint"`
}

type Usage struct {
	Meta              map[string]json.RawMessage `json:"_meta,omitempty"`
	CachedReadTokens  int64                      `json:"cachedReadTokens,omitempty"`
	CachedWriteTokens int64                      `json:"cachedWriteTokens,omitempty"`
	InputTokens       int64                      `json:"inputTokens"`
	OutputTokens      int64                      `json:"outputTokens"`
	ThoughtTokens     int64                      `json:"thoughtTokens,omitempty"`
	TotalTokens       int64                      `json:"totalTokens"`
}

type UsageUpdate struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
	Cost Cost                       `json:"cost,omitempty"`
	Size int64                      `json:"size"`
	Used int64                      `json:"used"`
}

type WaitForTerminalExitRequest struct {
	Meta       map[string]json.RawMessage `json:"_meta,omitempty"`
	SessionId  SessionId                  `json:"sessionId"`
	TerminalId TerminalId                 `json:"terminalId"`
}

type WaitForTerminalExitResponse struct {
	Meta     map[string]json.RawMessage `json:"_meta,omitempty"`
	ExitCode int64                      `json:"exitCode,omitempty"`
	Signal   string                     `json:"signal,omitempty"`
}

type WorkspaceFolder struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
	Name string                     `json:"name"`
	Uri  string                     `json:"uri"`
}

type WriteTextFileRequest struct {
	Meta      map[string]json.RawMessage `json:"_meta,omitempty"`
	Content   string                     `json:"content"`
	Path      string                     `json:"path"`
	SessionId SessionId                  `json:"sessionId"`
}

type WriteTextFileResponse struct {
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`
}
